cityofasheville/simplicity2

firebase.json

Fixed hosting to pass all urls through index.html since routing is handled by the app.

Added a rewrites section to firebase.json to send all URLs to index.html

---

docs/index.md
docs/resources-literature-concepts/declarative-events-vs-imperative-actions.md
docs/resources-literature-concepts/postcss-and-cssmodules.md
docs/resources-literature-concepts/react-apps-with-pages.md
docs/resources-literature-concepts/sagas.md

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.
**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.
Before opening a pull request, please ensure:
Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)
**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT …

Added jekyll front matter on all the docs pages

---

app/app.js
app/modules/User/user.js

It now gets the authentication token after login and saves it in session storage. It is then passed from there to the server, which gets it and adds it to the graphql context.

Auth token now being sent in authorization header to server

---

app/containers/SearchBox/SearchResults/searchResults.js
app/containers/SearchBox/searchBox.js
app/containers/SearchBox/searchBoxActions.js
app/containers/SearchBox/searchBoxConstants.js
app/containers/SearchBox/searchBoxMessages.js
app/containers/SearchBox/searchBoxReducer.js
app/containers/SearchBox/searchBoxStyles.css
app/containers/SearchBox/tests/actions.test.js
app/containers/SearchBox/tests/index.test.js
app/containers/SearchBox/tests/reducer.test.js
app/topics/development/citywide/DevelopmentDashboard/developmentDashboard.js
package.json

Ugly, but basic search is working.

Issue 31 searchcontext

---

app/components/DashboardPerformanceSummary/dashboardPerformanceSummary.js
app/components/DashboardPerformanceSummary/dashboardPerformanceSummaryStyles.css
app/containers/HomePage/homePage.js
package.json

Created a DashboardPerformanceSummary component. It's currently being used on the homepage for now.

Created a DashboardPerformanceSummary component

---

src/modules/utilities/budgetUtilities.js

…ilding, then added a function to walk the tree after and round all the values.

Fixed rounding in the buildTrees function in budgetUtilities.js

---

.babelrc
.eslintrc.json
package.json
yarn.lock

Example usage:
```js
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
console.log(x); // 1
console.log(y); // 2
console.log(z); // { a: 3, b: 4 }
```

Added object rest spread.

---

package.json
src/app/App.js
src/app/search/Search.js
src/gqlClient.js
src/resolvers.js
src/utilities/auth/authControl.js
src/utilities/auth/authProviderModal.js
src/utilities/auth/graphql/authDefaultState.js
src/utilities/auth/graphql/authMutations.js
src/utilities/auth/graphql/authQueries.js
src/utilities/auth/graphql/authResolvers.js
yarn.lock

Was using refreshToken incorrectly. Resolvers were not being merged properly.

Update user tokens and fix some state bugs

---

package.json

Eliminate writeToStore warnings with IntrospectionFragmentMatcher
Switched mergeProps out for modularized version.
Convert line chart and fix labeling on SLA bar chart

Version 2.2.4

---

src/app/budget/BudgetDetailsContainer.js
src/app/budget/BudgetDetailsTable.js
src/app/budget/BudgetDetailsTreemap.js
src/app/budget/BudgetSummary.js
src/app/budget/BudgetSummaryBarChart.js
src/app/budget/BudgetSummaryDetails.js
src/app/budget/SummaryDepartments.js
src/app/budget/SummaryUse.js
src/app/budget/budgetUtilities.js
src/app/budget/graphql/budgetQueries.js
src/shared/visualization/BarChart.js
src/shared/visualization/visUtilities.js

Reverts cityofasheville/simplicity2#356

Revert "410 budget updates"

---

package.json
webpack.config.js
yarn.lock

The dependency changes should improve our production bundle size and thus make our site slightly faster on slower internet connections. The webpack changes will allow the dev server to have proper source maps.

Some fixes for webpack and dependencies.

---

src/app/App.js
src/app/mini_search/MiniResults.js
src/app/mini_search/MiniSearch.js
src/app/search/Search.js
src/app/search/searchResults/SearchResultGroup.js
src/app/search/searchResults/SearchResults.js
src/app/search/searchResults/searchResultsUtils.js
src/styles/styles.scss
yarn.lock

Abstract common search results methods into a utils file. Use react table for mini search.

Paginate mini

---

package.json
src/app/development/trc/TRCDashboard.js
src/app/development/trc/TrcTimeline.js
src/app/development/trc/data.js
src/app/development/volume/YearlyPermitVol.js
src/shared/visualization/Tooltip.js
src/styles/components/TrcTimeline.scss
src/styles/components/YearlyPermitVol.scss
src/styles/components/components.scss
yarn.lock

Handle edge cases, fix styling for TRC and dev volume dashboards.

Vis cleanup

---

package.json
src/app/development/volume/BooleanSplitMultiples.js
src/app/development/volume/DataModal.js
src/app/development/volume/GranularDataReceivers.js
src/app/development/volume/GranularVolume.js
src/app/development/volume/PermitTypeMenus.js
src/app/development/volume/PermitVolCirclepack.js
src/app/development/volume/StatusDistributionMultiples.js
src/app/development/volume/VolumeHistogram.js
src/app/development/volume/granularUtils.js
src/app/internal/city_website_analytics/AnalyticsCirclePack.js
src/shared/visualization/HorizontalLegend.js
src/shared/visualization/Tooltip.js
src/styles/components/DataModal.scss
src/styles/components/GranularVolume.scss
src/styles/components/components.scss
src/styles/styles.scss
yarn.lock

Clean up sundry issues with granular volume dash

Clean up sundry issues with granular volume dash

---

src/app/development/volume/StatusDistributionMultiples.js
src/app/development/volume/granularUtils.js

Add possible mouse behavior for granular dash

Granular cleanup 2

---

src/app/development/volume/LoadingModal.js
src/app/development/volume/PermitVolume.js
src/styles/components/HierarchicalDropdown.scss

Add feedback link and make arrow on dropdown reverse

Permits cleanup 5

---

src/app/development/DevelopmentDashIndex.js
src/app/development/permits/Permit.js
src/app/development/permits/PermitsIndex.js
src/app/development/trc/MajorDevelopmentDashboard.js
src/shared/visualization/Accordion.js
src/styles/components/Permit.scss
src/styles/components/components.scss

Make detail page more reasonable, add accordion to FAQ as example

Format projects page

---

src/app/App.js
src/app/development/permits/PermitsIndex.js
src/app/development/trc/PermitsTable.js
src/app/development/trc/SectionNav.js
src/styles/components/MajorDevelopmentDashboard.scss
src/styles/styles.scss

Make permit tables searchable; deal with sticky sideways nav bug

Searchable permit tables

---

src/app/App.js
src/app/development/trc/AnnotatedDagre.js
src/app/development/trc/MajorDevelopmentDashboard.js
src/app/development/trc/SectionNav.js
src/app/development/trc/TRCDataTable.js
src/shared/visualization/Accordion.js
src/styles/components/Accordion.scss
src/styles/components/MajorDevelopmentDashboard.scss
src/styles/components/components.scss
src/styles/styles.scss

Make dash nav sidebar or accordion depending on whether under tablet size

Rearrange trc ed

---

src/app/development/trc/AnnotatedDagre.js
src/app/development/trc/utils.js
src/app/development/volume/TimeSlider.js
src/styles/components/MajorDevelopmentDashboard.scss

Restagger dagre

---

src/app/development/DevelopmentByAddress.js
src/app/development/DevelopmentByNeighborhood.js
src/app/development/DevelopmentByStreet.js
src/app/development/DevelopmentDetail.js
src/app/development/DevelopmentTable.js
src/app/development/permits/Permit.js
src/app/development/permits/PermitsTableWrapper.js
src/app/development/trc/AnnotatedDagre.js
src/app/development/trc/SectionNav.js
src/app/development/utils.js
src/app/development/volume/granularUtils.js
src/styles/components/MajorDevelopmentDashboard.scss

Add links, space out map data, change applicant_name to application_name.

General dsd cleanup

---

src/app/development/permits/Permit.js
src/app/development/permits/permitFieldFormats.js
src/app/development/utils.js
src/styles/components/Permit.scss

Add status translations, push to dev for sharing and iterating with DSD team

Add status translation

---

src/app/development/permits/Permit.js
src/app/development/permits/PermitSearchBar.js
src/app/development/permits/PermitSearchIndex.js
src/app/development/permits/PermitSearchResults.js
src/app/development/permits/PermitSearchResultsAddresses.js
src/app/development/permits/PermitSearchResultsByAddress.js
src/app/development/permits/PermitsIndex.js
src/app/development/permits/PermitsTable.js
src/app/development/trc/MajorDevelopmentDashboard.js
src/app/development/trc/textContent.js
src/shared/LoadingAnimation.js
src/styles/components/MajorDevelopmentDashboard.scss
src/styles/styles.scss

Permit search now works for application ID or address. Major Dev Dashboard links have been updated for clarity and inclusion of permit search.

Release of permit search by address

---

src/app/property/Property.js
src/app/property/SteepSlope.js
src/styles/components/DetailsGrouping.scss

Task: https://app.asana.com/0/1201508507497553/1201523074049331

Created a new component for ss.

---

src/app/property/SteepSlope.js

https://app.asana.com/0/1201508507497553/1201523074049327

Added spinner for steep slope.

---

src/app/address/Address.js
src/app/property/SteepSlope.js
src/shared/ClimateJustice.js
src/styles/components/DetailsGrouping.scss

https://app.asana.com/0/1201508507497553/1201534156608020

Added CJ card to Address page.

---

src/app/property/Property.js
src/shared/ClimateJustice.js
src/styles/components/DetailsGrouping.scss

Also added the link to the resiliency guide to the component.

Added cj component to property page

---

src/app/address/Address.js

Task: https://app.asana.com/0/1201508507497553/1201610993002482

Matched property layout.

---

src/app/street/Street.js

https://app.asana.com/0/1201508507497553/1201610993002486

Updated street layout.

---

src/app/Topics.js

https://app.asana.com/0/1201508507497553/1201534156608018

Added CJ icon-link to the Home page.

---

src/app/street/Street.js

https://app.asana.com/0/1201508507497553/1201624838812346

Moved the tiles below the map.

---

src/app/development/permits/PermitsIndex.js
src/app/development/permits/PermitsTable.js
src/app/development/permits/PermitsTableWrapper.js
src/app/development/trc/TRCDataTable.js
src/app/development/volume/TimeSlider.js

Fixes bugs with URL date params (primarily PermitsIndex and TimeSlider)
- date-related params are now ignored by PermitsTable when it mutates filter-related params
- now using URLSearchParams to handle query params
- improved validation of date input (milliseconds)

url param bug fixes
